//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgregarDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artista
    {
    
        public int id_artista { get; set; }
        public string nombre { get; set; }
        public Nullable<short> edad { get; set; }
        public Nullable<double> altura { get; set; }
        public Nullable<double> peso { get; set; }
        public virtual Manager Manager{ get; set; }
}
}
