//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgregarDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancion
    {
        public int id_cancion { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> duracion { get; set; }
        public string colaboradores { get; set; }
        public string dj { get; set; }
        public Nullable<int> id_artista { get; set; }
    
        public virtual Artista Artista { get; set; }
    }
}
