//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgregarDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descarga
    {
        public int id_descarga { get; set; }
        public Nullable<int> id_cancion { get; set; }
        public string proveedor { get; set; }
        public Nullable<double> duracion { get; set; }
        public string navegador { get; set; }
        public string formato { get; set; }
    
        public virtual Cancion Cancion { get; set; }
    }
}
