//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgregarDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public int id_manager { get; set; }
        public string nombre { get; set; }
        public Nullable<short> edad { get; set; }
        public string direccion { get; set; }
        public Nullable<double> sueldo { get; set; }
    
        public virtual Artista Artista { get; set; }
    }
}
