//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgregarDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MusicaEntities : DbContext
    {
        public MusicaEntities()
            : base("name=MusicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artista> Artista { get; set; }
        public virtual DbSet<Cancion> Cancion { get; set; }
        public virtual DbSet<Descarga> Descarga { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
    
        public virtual ObjectResult<seleccionarDescargas_SP_Result> seleccionarDescargas_SP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<seleccionarDescargas_SP_Result>("seleccionarDescargas_SP");
        }
    }
}
